name: Compose Plugin CI

on:
  push:
    tags: [ '20[0-9]+.[0-9]+.[0-9]' ]
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a Release T/F'
      version_letter:
        description: 'Additional Letter to add to the version'
        
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
      
    - name: Set Pre-Build ENV Variables
      if: github.event.inputs.version_letter
      run: |
          echo "UI_VERSION_LETTER=${{github.event.inputs.version_letter}}" >> $GITHUB_ENV
      
    - name: Build the in Docker
      run: |
        chmod +x ./build_in_docker.sh
        chmod +x ./source/pkg_build.sh
        ./build_in_docker.sh -u
   
    - name: Set Post-Build ENV Variables
      id: version
      run: echo "version=${{steps.date.outputs.date}}${{env.UI_VERSION_LETTER}}" >> $GITHUB_OUTPUT

    - name: Upload Artifact 
      uses: actions/upload-artifact@v2
      with:
        name: compose.manager-package-${{steps.version.outputs.version}}.txz
        path: ./archive/compose.manager-package-*

    - name: Set Release ENV Variables On Manual
      if: github.event_name == 'workflow_dispatch'
      run: |
          echo "DO_RELEASE=${{github.event.inputs.create_release}}" >> $GITHUB_ENV
          echo "RELEASE_TAG_NAME=${{steps.version.outputs.version}}" >> $GITHUB_ENV
          
    - name: Set Release ENV Variables On Auto
      if: github.event_name != 'workflow_dispatch'
      run: |
          echo "DO_RELEASE=T" >> $GITHUB_ENV
          echo "RELEASE_TAG_NAME=${{github.GITHUB_REF}}" >> $GITHUB_ENV
    - name: Calculate md5 of package
      if: env.DO_RELEASE == 'T'
      id: hash
      run: echo "md5=$(md5sum ./archive/compose.manager-package-${{steps.version.outputs.version}}.txz)" >> $GITHUB_OUTPUT
    - name: Update md5 and version in plg definition
      if: env.DO_RELEASE == 'T'
      run: |
          sed -i -e 's|<!ENTITY version  ".*">|<!ENTITY version  "${{steps.version.outputs.version}}">|' -e 's|<!ENTITY packageMD5  ".*">|<!ENTITY packageMD5  "${{steps.hash.outputs.md5}}">|' ./compose.manager.plg
    - name: Commit changes to repo
      if: env.DO_RELEASE == 'T'
      uses: stefanzweifel/git-auto-commit-action@v5
    - name: Create manual release
      id: upload-release-asset 
      uses: softprops/action-gh-release@v1
      if: env.DO_RELEASE == 'T'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{env.RELEASE_TAG_NAME}}
          name: Compose Manager Package ${{env.RELEASE_TAG_NAME}}
          body_path: ./archive/release_info
          draft: false
          prerelease: false
          files: ./archive/compose.manager-package-${{steps.version.outputs.version}}.txz
